version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Zipping Lambda function...
      - zip -r lambdaWS2.zip .

  post_build:
    commands:
      - echo Packaging and deploying CloudFormation stack...
      - aws cloudformation package --template-file template.yaml --s3-bucket your-code-s3-bucket --output-template-file packaged.yaml
      - aws cloudformation deploy --template-file packaged.yaml --stack-name pipelinePruebas --capabilities CAPABILITY_IAM

artifacts:
  files:
    - lambdaWS2.zip
    - template.yaml
