version: 0.2
phases:
  install:
    commands:
      - curl -Lo sam-installation https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip sam-installation -d sam-cli
      - ./sam-cli/install
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket lambdapoc-ci-cd-artifacts
artifacts:
  files:
    - packaged.yaml
