version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket lambdapoc-ci-cd-artifacts
artifacts:
  files:
    - packaged.yaml
