version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli --user
  build:
    commands:
      # Añadir SAM CLI al PATH
      - export PATH=$PATH:/root/.local/bin
      # Verificar que SAM CLI está instalado correctamente
      - sam --version
      # Ejecutar el build con SAM CLI
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket lambdapoc-ci-cd-artifacts

artifacts:
  files:
    - packaged.yaml
